### PR TITLE
CMS Twig extension `contentFunction()` should return bool like `partialFunction()`

### LINKED ISSUE #731: Test content file exists
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Pages

### Issue description

Hi,
I would like, in a CMS partial, test if a content file exists.
So I do :
```
                {% if content(<my_file.htm>) %}
                  {% content <my_file.htm> %}
                {% else %}
                  <something else>
                {% endif %}
```
If I do that, I have a twig error on my if line : `An exception has been thrown during the rendering of a template ("The content file '<my_URL>' is not found.").`

How can I do that ?

Thanks

### Steps to replicate

After a fresh install, just add the test

### Workaround

_No response_

### PR DESCRIPTION
**Pull request by mjauvin**
Fixes #731

### CODE REVIEW

File: modules/cms/classes/Controller.php [hunk 1]
```diff
@@ -1098,10 +1098,11 @@ public function renderPartial($name, $parameters = [], $throwException = true)
      *
      * @param string $name The content view to load.
      * @param array $parameters Parameter variables to pass to the view.
+     * @param bool $throwException Throw an exception if the content file is not found.
      * @throws SystemException If the content cannot be found
```
Comment (bennothommo) [inline modules/cms/classes/Controller.php]:
```suggestion
     * @throws SystemException If the content cannot be found, and `$throwException` is true.
```

File: modules/cms/classes/Controller.php [hunk 2]
```diff
@@ -1098,10 +1098,11 @@ public function renderPartial($name, $parameters = [], $throwException = true)
...
-     * @return string
+     * @return mixed Content file or false if not throwing an exception.
```
Comment (bennothommo) [inline modules/cms/classes/Controller.php]:
```suggestion
     * @return string|false Content file, or false if `$throwException` is false.
```

File: modules/cms/classes/Controller.php [hunk 3]
```diff
@@ -1127,7 +1128,11 @@ public function renderContent($name, $parameters = [])
          * Load content from theme
          */
         elseif (($content = Content::loadCached($this->theme, $name)) === null) {
-            throw new SystemException(Lang::get('cms::lang.content.not_found_name', ['name'=>$name]));
+            if ($throwException) {
+                throw new SystemException(Lang::get('cms::lang.content.not_found_name', ['name'=>$name]));
```
Comment (bennothommo) [inline modules/cms/classes/Controller.php]:
```suggestion
                throw new SystemException(Lang::get('cms::lang.content.not_found_name', ['name' => $name]));
```

**Review by bennothommo — CHANGES_REQUESTED** [review]

**Review by bennothommo — APPROVED** [review]
