### PR TITLE
Fix support for Winter Mix commands on Windows

### LINKED ISSUE #505: Laravel Mix is not working as expected on Windows Platform
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

## Summary
Laravel Mix implementation has issues on Windows 10. The newly implemted "mix:compile" and "mix:watch" commands have many issues preventing mix feature running. [Exact PHP version 8.0.14]

## Bug 1:

First of all, I found out that path concatenations are not cross platform safe. Because of this bug, relative paths can't be concatenated and the returnes something like "C:\path\to\root\C:\path\to\root\themes\foo-bar/mix.webpack.js".

Example issue from code:
```php
// System\Classes\MixAssets : Line 102

$this->registerPackage($name, $theme->getPath() . '/' . $file);
```

Should be:
```php
$this->registerPackage($name, $theme->getPath() . DIRECTORY_SEPARATOR . $file);
```
(PHP should have handled conversion but it didn't in this case)

Following classes in System module have this issue.

- System\Classes\MixAssets
- System\Console\MixWatch
- System\Console\MixCompile

Error message and log:
```powershell
PS F:\Dev\wn-laravel-mix-error> php artisan mix:compile --verbose
Mixing package "snowboard"

In Filesystem.php line 133:

  [ErrorException]
  file_put_contents(F:\Dev\wn-laravel-mix-error\F:\Dev\wn-laravel-mix-error\modules\system\assets\js\snowboard/mix.we
  bpack.js): Failed to open stream: No such file or directory


Exception trace:
  at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:133
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 file_put_contents() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:133
 Illuminate\Filesystem\Filesystem->put() at F:\Dev\wn-laravel-mix-error\vendor\winter\storm\src\Filesystem\Filesystem.php:243
 Winter\Storm\Filesystem\Filesystem->put() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
 Illuminate\Support\Facades\Facade::__callStatic() at F:\Dev\wn-laravel-mix-error\modules\system\console\MixCompile.php:206
 System\Console\MixCompile->createWebpackConfig() at F:\Dev\wn-laravel-mix-error\modules\system\console\MixCompile.php:148
 System\Console\MixCompile->mixPackage() at F:\Dev\wn-laravel-mix-error\modules\system\console\MixCompile.php:96
 System\Console\MixCompile->handle() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Container\Util.php:37
 Illuminate\Container\Util::unwrapIfClosure() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Container\Container.php:590
 Illuminate\Container\Container->call() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Console\Command.php:134
 Illuminate\Console\Command->execute() at F:\Dev\wn-laravel-mix-error\vendor\symfony\console\Command\Command.php:255
 Symfony\Component\Console\Command\Command->run() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Console\Command.php:121
 Illuminate\Console\Command->run() at F:\Dev\wn-laravel-mix-error\vendor\symfony\console\Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at F:\Dev\wn-laravel-mix-error\vendor\symfony\console\Application.php:273
 Symfony\Component\Console\Application->doRun() at F:\Dev\wn-laravel-mix-error\vendor\symfony\console\Application.php:149
 Symfony\Component\Console\Application->run() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Console\Application.php:93
 Illuminate\Console\Application->run() at F:\Dev\wn-laravel-mix-error\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:131
 Illuminate\Foundation\Console\Kernel->handle() at F:\Dev\wn-laravel-mix-error\artisan:35
```

---

## Bug 2:
After fixing the each one of the concatenations, compilation process couldn't run webpack.js in bin directory. A windows execution error window appeared on screen for "Microsoft JScript Error". "[Trying to execute a script...](https://stackoverflow.com/questions/37192508/trying-to-execute-a-script-from-package-json-on-windows-throws-a-jscript-error)" page on stackoverflow entry had some temporary solutions however system default is an issue. Thus, I tried to find main issue. 

"System\Console\MixCompile->createCommand()" tries to execute webpack directly however Windows does not start this script with Node.js. I tried removing .JS from PATHEXT but it didn't workout. Then selected node.exe as default program for .js files. It kind of worked but it was not a good workaround.

I removed webpack.js path then added "npx mix build/watch", changed "--config" to "--mix-config" and removed '--progress'; this worked for me. Still, this is not a good execution command.

Error Message:
```powershell
PS F:\Dev\wn-laravel-mix-error> php artisan mix:compile --verbose
Mixing package "snowboard"
Unknown command: "F:\Dev\wn-laravel-mix-error\node_modules\webpack\bin\webpack.js"

To see a list of supported npm commands, run:
  npm help
Unable to compile package "snowboard"
```

---

## Bug 3: 

require() function can't find 'laravel-mix' module when MixCompile executes the process. I didn't understand, but require removes the seperators in path somehow.

Error message:

```powershell
PS F:\Dev\wn-laravel-mix-error> php artisan mix:compile --verbose
Mixing package "snowboard"
[webpack-cli] Error: Cannot find module 'F:Devwn-laravel-mix-error/node_modules/laravel-mix/src/Engine'
Require stack:
- F:\Dev\wn-laravel-mix-error\modules\system\assets\js\snowboard\mix.webpack.js
- F:\Dev\wn-laravel-mix-error\node_modules\laravel-mix\setup\webpack.config.js
- F:\Dev\wn-laravel-mix-error\node_modules\webpack-cli\lib\webpack-cli.js
- F:\Dev\wn-laravel-mix-error\node_modules\webpack-cli\lib\bootstrap.js
- F:\Dev\wn-laravel-mix-error\node_modules\webpack-cli\bin\cli.js
- F:\Dev\wn-laravel-mix-error\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\Dev\wn-laravel-mix-error\modules\system\assets\js\snowboard\mix.webpack.js:2:40)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\Dev\\wn-laravel-mix-error\\modules\\system\\assets\\js\\snowboard\\mix.webpack.js',
    'F:\\Dev\\wn-laravel-mix-error\\node_modules\\laravel-mix\\setup\\webpack.config.js',
    'F:\\Dev\\wn-laravel-mix-error\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'F:\\Dev\\wn-laravel-mix-error\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'F:\\Dev\\wn-laravel-mix-error\\node_modules\\webpack-cli\\bin\\cli.js',
    'F:\\Dev\\wn-laravel-mix-error\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
Unable to compile package "snowboard"
```

Additional note:
- "$relativeMixJsPath" should be wrapped "base_path($relativeMixJsPath)" in some points of System\Console\MixCompile and System\Console\MixWatch

### Steps to replicate

1. Fresh installation of Winter CMS [Using SQLite is enough since no DB work needed]
2. Run "php artisan mix:install"
3. Run "php artisan mix:compile" *Bug 1 happens at this point*
4. Replace all '/' seperators on bugged classes with "DIRECTORY_SEPARATOR" constant [Overwriting old files with files in "bug-1-fix" branch of [wn-laravel-mix-error-fix](https://github.com/iamyigitkoc/wn-laravel-mix-error-fix) is enough]
5. Run "PHP artisan mix:compile" "Bug 2 happens at this point"
6. Fix $command in createCommand() of MixCompile class [Overwriting old files with files in "bug-2-fix" branch of [wn-laravel-mix-error-fix](https://github.com/iamyigitkoc/wn-laravel-mix-error-fix) is enough]
7.  Run "PHP artisan mix:compile" "Bug 3 happens at this point"

### Workaround

I provided some kind of "fixed" code in [wn-laravel-mix-error-fix](https://github.com/iamyigitkoc/wn-laravel-mix-error-fix) for Bug 1 and Bug 2 seperately.

[fixed-for-windows](https://github.com/iamyigitkoc/wn-laravel-mix-error-fix/tree/fixed-for-windows) branch is a workaround that makes running "php artisan mix:compile" or "php artisan mix:watch" possible. 

The last bug was caused by singular '\'. Window's separator was not revesed or escaped in webpack config file created via fixture. To fix this issue I added addslashes() escape function to every path value replaced in config file.

### Last words
- This is my first ever issue report on Winter community. Sorry if I did mistakes on my bug report.
- Much thanks to all contributors of Winter CMS and @LukeTowers for this powerful yet simple CMS platform.

### Edit 1:
Created a complete workaround.

### PR DESCRIPTION
**Pull request by iamyigitkoc**
Fixes #505

Added the windows fixes to the MixWatch, MixInstall console commands and MixAssets helper.

While working on the fix, I also found out that new pcntl_signal signal handlers doesn't work on Windows too. (Since it's based on POSIX signals) This is also fixed on MixWatch command via detecting the OS.

The fix is tested on both Ubuntu 18.04.6 LTS through WSL 2 and Windows 10 21H1 build 19043.1766.

**Before merging, it's highly suggested to test the fix on a non-wsl Linux based system for QA.**

### CODE REVIEW

File: modules/system/console/MixCompile.php [hunk 1]
```diff
@@ -81,7 +81,7 @@ public function handle(): int
 
         foreach ($registeredPackages as $name => $package) {
             $relativeMixJsPath = $package['mix'];
-            if (!$this->canCompilePackage($relativeMixJsPath)) {
+            if (!$this->canCompilePackage(base_path($relativeMixJsPath))) {
```
Comment (LukeTowers) [inline modules/system/console/MixCompile.php]: Why is this required?

File: modules/system/console/MixCompile.php [hunk 2]
```diff
@@ -180,7 +180,9 @@ protected function createCommand(string $mixJsPath): array
         $command = $this->argument('webpackArgs') ?? [];
         array_unshift(
             $command,
-            $basePath . '/node_modules/webpack/bin/webpack.js',
+            "npx",
+            "webpack",
+            "build",
```
Comment (LukeTowers) [inline modules/system/console/MixCompile.php]: Why is this required?

File: modules/system/console/MixCompile.php [hunk 3]
```diff
@@ -197,7 +199,7 @@ protected function createWebpackConfig(string $mixJsPath): void
 
         $config = str_replace(
             ['%base%', '%notificationInject%', '%mixConfigPath%', '%pluginsPath%', '%appPath%'],
-            [$basePath, '', $mixJsPath, plugins_path(), base_path()],
+            [addslashes($basePath), '', addslashes($mixJsPath), addslashes(plugins_path()), addslashes(base_path())],
```
Comment (LukeTowers) [inline modules/system/console/MixCompile.php]: Why is this required?

File: modules/system/console/MixWatch.php [hunk 4]
```diff
@@ -115,9 +120,12 @@ public function handleSignal(int $signal): void
...
 
-        // Exit cleanly at this point, if this was a user termination
-        if ($signal === SIGINT || $signail === SIGQUIT) {
-            exit(0);
+        //Windows fix for signal issue
+        if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
+            // Exit cleanly at this point, if this was a user termination
+            if ($signal === SIGINT || $signail === SIGQUIT) {
+                exit(0);
+            }
```
Comment (LukeTowers) [inline modules/system/console/MixWatch.php]: Would you be willing to add support for Window's equivalent API to handle console command cleanup? See https://stackoverflow.com/questions/9523240/php-cli-in-windows-handling-ctrl-c-commands/60519075#60519075

File: modules/system/console/MixCompile.php (hunk 1 above)
Comment (iamyigitkoc) [reply modules/system/console/MixCompile.php]: relativeMixJsPath was not correctly run on npx thus base_path resolves this issue by providing fully qualified path of the project. Also, it makes the path explicit.

File: modules/system/console/MixCompile.php (hunk 3 above)
Comment (iamyigitkoc) [reply modules/system/console/MixCompile.php]: While resolving the path, somehow php removes the slashes and it causes the following error in mix:

Error: Cannot find module 'D:DevWintercmsfixed-test/node_modules/laravel-mix/src/Engine'

Addslashes fixes the previously removed slashes.

File: modules/system/console/MixCompile.php (hunk 2 above)
Comment (iamyigitkoc) [reply modules/system/console/MixCompile.php]: Windows won't run scripts in powershell without correct privilidges. Rather than loading the webpack script directly, running it with npx will solve this issue. However without definition of "npx" in %path% environment variable, it may cause running issue.

File: modules/system/console/MixWatch.php (hunk 4 above)
Comment (iamyigitkoc) [reply modules/system/console/MixWatch.php]: I can add the signal handling this week :) 👍

Comment (LukeTowers) [reply modules/system/console/MixWatch.php]: @iamyigitkoc are you able to add the cleanup functionality for Windows based on that stackoverflow link?

**Comment by bennothommo** [comment]
@iamyigitkoc I've just added Windows signal handling - could you give that a try for us and let us know if that works? I'll do the same with Linux.

**Comment by LukeTowers** [comment]
@bennothommo any ideas for a cleaner API to implement on the base Winter Storm Console command class so that we can do something like:

```
public function onTerminate()
{

}
``` 

in the extending classes so they don't have to muck about with linux vs Windows termination handling?

**Comment by bennothommo** [comment]
@LukeTowers I wonder if it's something we should probably implement upstream?

**Comment by LukeTowers** [comment]
Nah, not worth the effort to implement on Symfony or Laravel, better to just do it on our base class for now.

**Comment by bennothommo** [comment]
Supposedly, CTRL+C in Windows is still considered a SIGINT signal. I'm not sure if the current commands pick it up though or if it needs the Windows signal handler - without a Windows environment to test, I'm unable to tell :(.

**Comment by iamyigitkoc** [comment]
I was on vacation. Going to test the fix on Windows env. now. I have also implemented a fix for the signal handling. To implement it on core, maybe creating a wrapper for SignalRegistry and extension to SignalableCommandInterface can be a solution. @LukeTowers @bennothommo

File: modules/system/classes/MixAssets.php [hunk 5]
```diff
@@ -110,7 +110,7 @@ public function init()
         // Search modules for Mix packages to autoregister
         foreach ($enabledModules as $module) {
             $module = strtolower($module);
-            $path = base_path("modules/$module") . '/' . $this->mixJs;
+            $path = base_path("modules" . DIRECTORY_SEPARATOR . "$module") . DIRECTORY_SEPARATOR . $this->mixJs;
```
Comment (iamyigitkoc) [inline modules/system/classes/MixAssets.php]: The directory seperator is a global PHP variable which depends on the OS. Rather than hard coding the directory seperators, using this variable makes the code independent of OS.

File: modules/system/console/MixCompile.php [hunk 6]
```diff
@@ -146,8 +147,8 @@ protected function canCompilePackage(string $mixJsPath): bool
         }
 
         $workspacesPackages = $this->packageJson['workspaces']['packages'] ?? [];
-
-        return in_array($this->getPackagePath($mixJsPath), $workspacesPackages);
+        $packagePathUnix = Str::replace("\\","/", $this->getPackagePath($mixJsPath));
```
Comment (iamyigitkoc) [inline modules/system/console/MixCompile.php]: While checking the path of the mixJs, the PHP interpreter handles directories with "\" directory seperator. However, to make install process crossplatform paths are written with "/" directory seperator in package.json. While checking the exitence of modules, the windows directory seperators should be replaced with "/". This code handles the process of conversion.

File: modules/system/console/MixCompile.php [hunk 7]
```diff
@@ -221,7 +224,7 @@ protected function createWebpackConfig(string $mixJsPath): void
 
         $config = str_replace(
             ['%base%', '%notificationInject%', '%mixConfigPath%', '%pluginsPath%', '%appPath%', '%silent%'],
-            [$basePath, '', $mixJsPath, plugins_path(), base_path(), (int) $this->option('silent')],
+            [addslashes($basePath), 'mix._api.disableNotifications();', addslashes($mixJsPath), addslashes(plugins_path()), addslashes(base_path()), (int) $this->option('silent')],
```
Comment (iamyigitkoc) [inline modules/system/console/MixCompile.php:230]: addslashes adds escaping to the raw characters in the string.

File: modules/system/console/MixInstall.php [hunk 8]
```diff
@@ -184,7 +184,8 @@ public function handle(): int
                 $this->info(
                     sprintf('Adding %s (%s) to the workspaces.packages property in package.json', $name, $package['path'])
                 );
-                $workspacesPackages = array_merge($workspacesPackages, [$package['path']]);
+                //Since director seperator differently on Windows platform, each "\" replaced with "/"
+                $workspacesPackages = array_merge($workspacesPackages, [Str::replace("\\","/",$package['path'])]);
```
Comment (iamyigitkoc) [inline modules/system/console/MixInstall.php]: While writing to the package.json, all "\" characters converted to "/" to output a unix based path.

File: modules/system/console/MixWatch.php [hunk 9]
```diff
@@ -60,6 +60,12 @@ public function handle(): int
             sprintf('Watching package "%s" for changes', $name)
         );
         $this->mixJsPath = $relativeMixJsPath;
+
+        // Create Windows signal handler
+        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' && function_exists('sapi_windows_set_ctrl_handler')) {
+            sapi_windows_set_ctrl_handler([$this, 'handleWindowsSignal'], true);
+        }
```
Comment (iamyigitkoc) [inline modules/system/console/MixWatch.php:67]: The conflicting signal handling code merged with @bennothommo's commit https://github.com/wintercms/winter/commit/452bb4222351b1a6d3cc0288a30804ebeb37234d

File: modules/system/console/MixWatch.php [hunk 10]
```diff
@@ -93,7 +99,7 @@ protected function createWebpackConfig(string $mixJsPath): void
 
         $config = str_replace(
             ['%base%', '%notificationInject%', '%mixConfigPath%', '%pluginsPath%', '%appPath%', '%silent%'],
-            [$basePath, 'mix._api.disableNotifications();', $mixJsPath, plugins_path(), base_path(), (int) $this->option('silent')],
+            [addslashes($basePath), 'mix._api.disableNotifications();', addslashes($mixJsPath), addslashes(plugins_path()), addslashes(base_path()), (int) $this->option('silent')],
```
Comment (iamyigitkoc) [inline modules/system/console/MixWatch.php:102]: Fixed charachter escapes and fixed wrong parantheses order for silent option.

File: modules/system/console/MixWatch.php [hunk 11]
```diff
@@ -106,6 +112,11 @@ protected function createWebpackConfig(string $mixJsPath): void
      */
     public function getSubscribedSignals(): array
     {
+        //Return empty subscribed signals to the Symfony Console Application Bootloader.
+        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
+            return [];
```
Comment (iamyigitkoc) [inline modules/system/console/MixWatch.php:117]: The conflicting signal handling code merged with @bennothommo's commit https://github.com/wintercms/winter/commit/452bb4222351b1a6d3cc0288a30804ebeb37234d

File: modules/system/console/MixWatch.php [hunk 12]
```diff
@@ -122,4 +133,21 @@ public function handleSignal(int $signal): void
...
         }
     }
+
+    /**
+     * Handles the provided Windows process singal.
+     */
+    public function handleWindowsSignal(int $event): void
+    {
+        if ($event === PHP_WINDOWS_EVENT_CTRL_C || $event === PHP_WINDOWS_EVENT_CTRL_BREAK) {
+            // Cleanup
```
Comment (iamyigitkoc) [inline modules/system/console/MixWatch.php:143]: The conflicting signal handling code merged with @bennothommo's commit https://github.com/wintercms/winter/commit/452bb4222351b1a6d3cc0288a30804ebeb37234d

File: modules/system/console/MixCompile.php [hunk 13]
```diff
@@ -4,6 +4,7 @@
 use Winter\Storm\Console\Command;
 use Symfony\Component\Process\Process;
 use System\Classes\MixAssets;
+use Winter\Storm\Support\Str;
```
Comment (iamyigitkoc) [inline modules/system/console/MixCompile.php:7]: Str helper is used in the commit to handle replacement

**Comment by iamyigitkoc** [comment]
@bennothommo tested the signal handling on windows. It works as expected.  👍

**Comment by bennothommo** [comment]
I've tested this on Linux and all commands are still running as expected, so if @iamyigitkoc is able to confirm all commands are running correctly on Windows, and the other @wintercms/maintainers have no objections, this is good to merge!

**Review by bennothommo — APPROVED** [review]

**Comment by LukeTowers** [comment]
I'll take another look on Sunday

**Comment by damsfx** [comment]
> I've tested this on Linux and all commands are still running as expected, so if @iamyigitkoc is able to confirm all commands are running correctly on Windows, and the other @wintercms/maintainers have no objections, this is good to merge!

I just did my own tests.

## On WSL : 

After `php artisan mix:install`, file `/package.json` changed to 
```json
{
    "devDependencies": {
        "laravel-mix": "^6.0.41"
    },
    "workspaces": {
        "packages": [
            "modules/backend",
            "modules/system",
            "plugins/winter/tailwindui",
            "themes/workshop"
        ]
    }
}
```

### Successfull tested commands : 
 - `php artisan mix:update`
 - `php artisan mix:list`
 - `php artisan mix:watch theme-workshop`
 - `php artisan mix:watch theme-workshop -f`
 - `php artisan mix:compile -p theme-workshop`
 - `php artisan mix:compile -p theme-workshop -f`

## On Windows environment : 

After `php artisan mix:install`, file `/package.json` changed to 
```json
{
    "devDependencies": {
        "laravel-mix": "^6.0.41"
    },
    "workspaces": {
        "packages": [
            "modules/backend",
            "modules/backend",
            "modules/system",
            "modules/system",
            "plugins/winter/tailwindui",
            "themes/workshop"
        ]
    }
}
```

### Successfull tested commands : 
 - `php artisan mix:update`
 - `php artisan mix:list`
 - `php artisan mix:watch theme-workshop`
 - `php artisan mix:watch theme-workshop -f`
 - `php artisan mix:compile -p theme-workshop`
 - `php artisan mix:compile -p theme-workshop -f`

## Conclusion
**From my tests, all seems to work as expected.**  

The only notable difference is the `/package.json` file which contains a duplicate `modules/...` entries when running `mix:install` command **on winddows**.  
The same behaviour occurs when I run the `mix:update` command, all package entries in `packages.json` are duplicated each time the command is run.   
Still under windows, the command `mix:update` always asks the question *package.json will be modified. Continue? (yes/no)*.

**Comment by iamyigitkoc** [comment]
> > I've tested this on Linux and all commands are still running as expected, so if @iamyigitkoc is able to confirm all commands are running correctly on Windows, and the other @wintercms/maintainers have no objections, this is good to merge!
> 
> I just did my own tests.
> 
> ## On WSL :
> After `php artisan mix:install`, file `/package.json` changed to
> 
> ```json
> {
>     "devDependencies": {
>         "laravel-mix": "^6.0.41"
>     },
>     "workspaces": {
>         "packages": [
>             "modules/backend",
>             "modules/system",
>             "plugins/winter/tailwindui",
>             "themes/workshop"
>         ]
>     }
> }
> ```
> 
> ### Successfull tested commands :
> * `php artisan mix:update`
> * `php artisan mix:list`
> * `php artisan mix:watch theme-workshop`
> * `php artisan mix:watch theme-workshop -f`
> * `php artisan mix:compile -p theme-workshop`
> * `php artisan mix:compile -p theme-workshop -f`
> 
> ## On Windows environment :
> After `php artisan mix:install`, file `/package.json` changed to
> 
> ```json
> {
>     "devDependencies": {
>         "laravel-mix": "^6.0.41"
>     },
>     "workspaces": {
>         "packages": [
>             "modules/backend",
>             "modules/backend",
>             "modules/system",
>             "modules/system",
>             "plugins/winter/tailwindui",
>             "themes/workshop"
>         ]
>     }
> }
> ```
> 
> ### Successfull tested commands :
> * `php artisan mix:update`
> * `php artisan mix:list`
> * `php artisan mix:watch theme-workshop`
> * `php artisan mix:watch theme-workshop -f`
> * `php artisan mix:compile -p theme-workshop`
> * `php artisan mix:compile -p theme-workshop -f`
> 
> ## Conclusion
> **From my tests, all seems to work as expected.**
> 
> The only notable difference is the `/package.json` file which contains a duplicate `modules/...` entries when running `mix:install` command **on winddows**. The same behaviour occurs when I run the `mix:update` command, all package entries in `packages.json` are duplicated each time the command is run. Still under windows, the command `mix:update` always asks the question _package.json will be modified. Continue? (yes/no)_.

I think the duplicate package beahviour occurs because of a comparison implemented on code. I will try to find it and fix it now :)

**Comment by iamyigitkoc** [comment]
I have fixed the duplicate package issue on the last commit. 

I have also validated and verified the console commands with last commit, they work as expected by design.

**Comment by damsfx** [comment]
> I have fixed the duplicate package issue on the last commit.
> 
> I have also validated and verified the console commands with last commit, they work as expected by design.

All looking good to me! 👍

**Review by bennothommo — APPROVED** [review]

**Comment by bennothommo** [comment]
Great work with this PR, @iamyigitkoc! :tada:

File: modules/system/console/MixCompile.php [hunk 14]
```diff
@@ -221,7 +227,7 @@ protected function createWebpackConfig(string $mixJsPath): void
 
         $config = str_replace(
             ['%base%', '%notificationInject%', '%mixConfigPath%', '%pluginsPath%', '%appPath%', '%silent%'],
-            [$basePath, '', $mixJsPath, plugins_path(), base_path(), (int) $this->option('silent')],
+            [addslashes($basePath), 'mix._api.disableNotifications();', addslashes($mixJsPath), addslashes(plugins_path()), addslashes(base_path()), (int) $this->option('silent')],
```
Comment (LukeTowers) [inline modules/system/console/MixCompile.php:230]: @bennothommo @iamyigitkoc why was it required to add the `mix._api.disableNotifications();` item?
